name: pocket-js-server

services:
  db:
    image: postgres:10.22-alpine3.16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pocket_net
  
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432/inorbit
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["sh", "-c", "npm run dev"]
    networks:
      - pocket_net
  
volumes:
  pgdata:

networks:
  pocket_net:
    driver: bridge